### ISSUE TITLE
Using TunneLS to make client TLS enabeld

### ISSUE THREAD

**Issue by nfoonf** [nhooyr/TunneLS#2]
Hi,

More a question than an issue: 
Is it possible to use TunneLS in a way that it unwraps TLS for a non TLS-enabled client?
I have a TLS-secured REST-API in a docker environment. One API-Consumer has no TLS-Support.
Is it Possible to place TunneLS between this client and the API? 
I tried this, but it seems it does not work?
Do I have to use client mode? 

my config:

```
{
        "Nodes": [
                {
                        "Name": "tls-wrapper",
                        "Mode": "client",
                        "Accept": "0.0.0.0:5002",
                        "Connect": "192.168.99.109:3376",
                        "Cert": "/etc/docker/cert.pem",
                        "Key": "/etc/docker/key.pem",
                        "CA": "/etc/docker/cert.pem",
                        "InsecureSkipVerify": true
                }
        ],
        "StdErrLogging": true,
        "StdErrPrefix": true
}
```

Some help would be highly appreciated...

**Comment by nhooyr** [comment]
What do you mean it doesn't work? Config looks good to me.

**Comment by nhooyr** [comment]
Oh, you needed to use server mode.
